name: Run Tests

on:
  # Trigger the workflow on pushes to main branch and on pull requests
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_and_integration_tests:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Run unit and integration tests with coverage
      - name: Run unit and integration tests
        run: npm run test:coverage

      # Upload coverage reports as a workflow artifact (if coverage is generated)
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit-tests
          path: coverage

  e2e_tests:
    name: End‑to‑end tests
    runs-on: ubuntu-latest
    needs: unit_and_integration_tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Install the Playwright browsers.  The `--with-deps` flag installs system dependencies required for the browsers to run
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run the Playwright end‑to‑end tests using project script if available
      - name: Run e2e tests
        run: npm run test:e2e

      # Upload Playwright traces and reports
      - name: Upload Playwright results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
